### ISSUE TITLE
Alex doesn't die when falling into a bottomless area...

### ISSUE THREAD

**Issue by ardvark71** [Secretchronicles/TSC#431] opened 2015-06-09 11:45 UTC
Hi all...

As I've mentioned here at the TSC forum...

http://forum.secretchronicles.de/topics/254?page=1#p1207

Since installing Beta 8, a couple times when I've fallen off a cliff or a ledge into a bottomless area, Maryo doesn't die. Instead, he seems to drop below the bottom of the screen (and out of site) and I'm able to make him go right or left a short distance. While I'm able to shoot projectiles, I'm not able to jump or somehow get him back up to the screen where I can see him.

When this has happened, I've had to exit the game and drop back to the menu to start over again. I've included a couple screenshots but I don't have the equipment and/or know how to make videos, plus the two times this has happened has been at totally at random. 

If more information is needed, please let me know... :-)

EDIT: Whoops, this may not be a bug after all, at least in the second screenshot (actually, a little bit before, I think.) I see by the placement of the jewels between the pipes, that landing below the screen is part of the game in this particular spot. However, I can't do anything apart from shooting projectiles and move a little ways right or left. This a totally new feature that I wasn't used to.

![1](https://cloud.githubusercontent.com/assets/12812795/8056946/e46bfeaa-0e61-11e5-812e-6dd171040558.png)

![2](https://cloud.githubusercontent.com/assets/12812795/8056955/f83b55d4-0e61-11e5-9277-1463c956f2ab.png)

**Comment by datahead8888** [comment] 2015-06-10 04:38
@ardvark71, at what position were you on the screen before falling in each of the pictures?  If it's not feasible to get a picture that shows this, can you describe it?

What level and world are each of the screenshots from?

> Whoops, this may not be a bug after all, at least in the second screenshot (actually, a little bit before, I think.) I see by the placement of the jewels between the pipes, that landing below the screen is part of the game in this particular spot.

It could still be an opportunity with the camera or level design, but we'll know once someone reproduces it.

**Comment by ardvark71** [comment] 2015-06-10 07:19
Hi Datahead...

I was able to reproduce the events just a few minutes ago in the same locations. They are both in World 2, the top screenshot (forest) is in "lvl_10" and the bottom one (pipes) is in "dj_kirby_1."

In the top screenshot, I fell off in the bottomless area just a hair left of what is shown in the screenshot but I could walk to the area that is shown.

In the bottom screenshot, I fell off just to the left of the pipe on the far left. The two saw blades on the twisty wooden pole is directly to the right of this same pipe.

BTW, how do I label this report as a bug (that are red in color,) or do you do that once it's confirmed?

Hope this helps...

**Comment by DarkAceZ** [comment] 2015-06-10 11:42
I believe I've run into this several times as well as @Quintus ... Still not sure what causes it, though.
It's a long shot, but perhaps it's caused by G-O-D mode? Were you using it at all in these game sessions? (hold the buttons 'G' 'O' 'D' while in-game to trigger funky GOD mode)

>BTW, how do I label this report as a bug (that are red in color,) or do you do that once it's confirmed?
Only certain people have this access, which I think is a little strange on github's part. At least the issue starter should be able to add his own tags, but that's not how it is...

**Comment by ardvark71** [comment] 2015-06-10 16:05
Hi AceZ...

No, I've used this mode before on Super Maryo Chronicles and I definately was not using it when these events happened. Actually, I've not used it once in Dr. M.

Thanks for adding the bug label, much appreciated. :-)

Regards...

**Comment by Quintus** [comment] 2015-06-10 16:28
I can confirm this bug exists, I have experienced it previously as well (even before beta 8 if I remember correctly). Last time I wanted to pin it down I was unable to reproduce it at will. Can anyone of you try to build a definitive guide to make this bug appear that works almost always? Please be as specific as you can, ideally with a step-by-step guide.

> Only certain people have this access, which I think is a little strange on github's part. At least the issue starter should be able to add his own tags, but that's not how it is...

Yet another reason for switching off to our system.

Valete,
Quintus

**Comment by ardvark71** [comment] 2015-06-10 17:16
Hi Quintus...

You should be able to duplicate it especially on the second map, "dj_kirby_1," right where I indicated on the screenshot. Just fall off right to the left of the pipe that has the two sawblades directly to the right of it. :-)

Thanks!

**Comment by sauer2** [comment] 2015-06-10 20:34
I had this bug too some months ago.

It probably happens after you get piped into another level.

Am 10.06.2015 um 19:16 schrieb ardvark71:

**Comment by sydneyjd** [comment] 2015-06-10 21:12
I noticed this bug in beta 7, but i thought it only showed up when i played around with GOD mode. aparently i was wrong.

**Comment by Quintus** [comment] 2015-06-11 14:38
I can’t get it to reproduce. I play dj_kirby_1 until I come to the passage with the two stacked saws. I then let me fall off to the left of that pipe that has the saws attached to its right, and I get killed.

I need some more reliable reproduction info. Please, you all help me here?

Valete,
Quintus

**Comment by sauer2** [comment] 2015-06-11 16:07
Did you get warped there from another level?

Am 11.06.2015 um 16:38 schrieb Marvin Gülker:

**Comment by datahead8888** [comment] 2015-06-12 14:27
I reproduced the bug in dj_kirby_1.
I consistently died when falling into pits in the level.  At this point I was saving my game and reloading each time, trying to reproduce it.  I then played dj_kirby_1_sub from the menu, beat that level, and then loaded my save point from dj_kirby_1.  At that point, jumping into a pit, the bug occurred.  I was able to produce this with the pit between any of the pipes shown in the screenshot.

I then tried loading my desert_break_in level and jumped into a pit.  The bug happened there, too.  Restarting the entire game executable solved this.

This of course is not authoritative and does not guarantee you will be able to reproduce it.  I can try to do this from scratch again later, but at least it's something for now.  This bug does seriously break the game, so I agree we should consider delaying the release for it unless someone can provide information to the contrary.

Video:
https://www.youtube.com/watch?v=UyjO2ygAn_s&feature=youtu.be

Save state file:
https://drive.google.com/file/d/0B6YSsocq3-cWWk5DZzcxUUZJYzA/view?usp=sharing

**Comment by Quintus** [comment] 2015-06-12 18:47
O_o What a strange bug!

I can second what @datahead8888 said, and thereby validify @sauer2’s statement. To reproduce:

1. Start TSC
2. In the menu, select `dj_kirby_1_sub`.
3. Finish the level by entering the pipe on the left.
4. You are taken  back to the menu. Now load `dj_kirby_1`.
5. Play until you find any abyss.
6. Ensure you have God mode disabled. Jump into the abyss.
7. You do not die. Instead, Alex falls eternally.

Step 7 doesn’t work if you have God mode enabled, the God mode exception in the abyss code will make you jump when hitting the bottom edge.

Okay, now that I can reproduce it with certainty, I can take a look at this. Strange thing, this. Really. What puzzles me most is that the bug stretches over multiple levels, but there might be an explanation for this. I have worked with TSC’s level code a lot, and in case you didn’t know, TSC does not destroy the `cLevel_Player` instance. That is, the level player *is always the same* instance. What one level sets on it is taken over into any following level. This is poor design, and I don’t have this in the SFML branch. I’m pretty sure a level exit sets some property on the level player instance that doesn’t get cleared.

Valete,
Quintus

**Comment by Quintus** [comment] 2015-06-12 19:04
If you have linking problems compiling older commits, use this CMakeLists.txt instead: http://team.secretchronicles.de/~quintus/stuff/CMakeLists.txt

Vale,
Quintus

**Comment by Quintus** [comment] 2015-06-12 19:51
`$ git bisect` found the problematic commit.

~~~~~~~~~~~~~~~~~
% git bisect bad
188e0bcb14cbf70557dcfcffde7d63552fe3bb55 is the first bad commit
commit 188e0bcb14cbf70557dcfcffde7d63552fe3bb55
Author: Quintus <quintus@quintilianus.eu>
Date:   Fri Feb 13 10:48:22 2015 +0100

    Add warping kill protection. Fixes #358.

:040000 040000 0a8aab4875688896ea715e0c4f89da53e62be5fc 93f7bbb5660a904d17f62e9cf3d7df0593ab338b M	tsc
~~~~~~~~~~~~~~~~~

So now for fixing.

Valete,
Quintus

**Comment by Quintus** [comment] 2015-06-12 19:56
I won’t do this for now as I’m working on the SFML stuff. With the faulty commit being pointed out, fixing this should be easy.

Valete,
Quintus

**Comment by datahead8888** [comment] 2015-06-14 11:28
This is now marked as blocker, since we have determined we cannot release until this issue is fixed.

**Comment by ardvark71** [comment] 2015-06-15 05:20
Thank you all for looking in to this and to Quintus (and possibly others) for ascertaining the exact issue and, Lord willing, creating a solution. :-)

Regards...

**Closed** 2015-06-18 16:40 UTC
Labels: Bug

**Comment by ardvark71** [comment] 2015-06-18 18:46
Awesome, perhaps I can test this in a later release! Thanks! :-)
