### ISSUE TITLE
Screen left in a horrible state if the game crashes

### ISSUE THREAD

**Issue by kirbyfan64** [Secretchronicles/TSC#414] opened 2015-04-18 18:06 UTC
If the game crashes (i.e. an exception is thrown), it leaves the screen how TSC set it. In my case, it left the screen an 1024x768 instead of my normal res, 1388x768. I'm guessing a catch block should be added in the main loop that resets the resolution to how it originally was.

Also, using `(void)` as the argument list (such as in `Init_Game`) isn't useful in C++.

**Comment by Quintus** [comment] 2015-04-21 08:11
> Also, using (void) as the argument list (such as in Init_Game) isn't useful in C++.

This is legacy code. The codebase stems from over 10 years ago! Back then it was required for some compilers to indicate empty argument lists with `void`.

As for the main problem: I have noticed this also, but as part of our move to SFML this problem will probably resolve by itself.

Vale,
Quintus

**Comment by Quintus** [comment] 2016-07-23 19:51
@kirbyfan64 Is this still relevant with the SFML port completed? Just modify the code to throw an exception or segfault somewhere to try.

Vale,
Quintus

**Comment by Quintus** [comment] 2018-06-06 15:50
I can confirm the problem still exists, but I'm unsure how to remedy it. To reproduce, add a `throw` statement somewhere you can foresay when it will be triggered. Then, compile, start the game, switch to fullscreen mode (ALT+ENTER) and trigger the `throw` statement. Your monitor will be left in the resolution the game had.

I suppose that the cleanup code for the screen resolution runs in `sf::RenderWindow`'s destructor, but since the RenderWindow instance contained in `pVideo` is properly `delete`d in `pVideo`'s destructor, I don't know why this happens. Don't destructors run in case of exceptions and/or segfaults?

**Comment by Quintus** [comment] 2018-06-06 15:52
Ah, it might be this: It is `pVideo`'s destructor that isn't run, because `pVideo` is `delete`d in main.cpp's `Exit_Game()` function, and that function is not run if the game crashes. Placing `pVideo` onto the stack would resolve this, but is this possible without breaking all the legacy code?

**Comment by Quintus** [comment] 2018-06-06 16:01
Well, placing `pVideo` on the stack does not solve the problem, even though it doesn't break legacy stuff.

**Comment by Quintus** [comment] 2018-06-06 16:08
Reason: `terminate()` gets called without the stack being unwound. https://stackoverflow.com/questions/222175/why-destructor-is-not-called-on-exception

**Comment by Quintus** [comment] 2018-06-06 16:32
There is only so much we can do here. There's no reasonable way to clean up after segfaults; this is the operating system's duty. Cleaning up after C++ exceptions is possible, but requires using `try ... catch` in the `main()` function, which means unwinding the stack and losing the possibility to obtain a stacktrace with GDB (firing GDB on an exception re-thrown with a bare `throw()` statement will point you only to the re-throw statement, not the original exception).

I will do a compromise. If TSC is compiled in debug mode, there will be no cleanup so faciliate the developer's life when using GDB. If TSC is compiled in release mode, there will be a `catch ... throw` construct in `main()` which will catch any exception, suggest filing a bug, call the cleanup function `Exit_Game()`, and then re-throw.

As a consequence, crashing with a C++ exception in release mode will restore your original screen resolution, while in debug mode it will not (instead, in debug mode you are granted better GDB usability). If the game crashes with a segfault, there is no difference -- it will just crash without cleanup. Since the memory is corrupt, there's nothing one can sensibly do.

Since this issue is thus impossible to completely fix, I mark it as WONTFIX.

**Closed** 2018-06-06 16:40 UTC
Labels: Bug, Wontfix

**Comment by pirate486743186** [comment] 2019-05-10 12:01
Isn't this a library bug/limitation? In SFML?
It should rescale the game, instead of changing the screen....

Maybe open a ticket with them?
https://github.com/SFML/sfml/issues

**Comment by Quintus** [comment] 2019-05-10 12:11
No, this is not a bug in SFML at all. It's a problem with C++ exceptions. Take a look at my explanations above, the linked Stackoverflow post, and the commit referenced above. It has nothing to do with SFML, but with when our own `Exit_Game()` function is (not) called.

**Comment by pirate486743186** [comment] 2019-05-10 12:16
you have it backwards.
the resolution of the screen should not have changed to begin with. The game should stretch it self....

**Comment by Quintus** [comment] 2019-05-10 12:35
>the resolution of the screen should not have changed to begin with. The game should stretch it self....

I don't understand what you want to say with that. The game can't foresee if it's going to crash further down the road.

TSC at startup requests full screen from SFML if configured in the preferences ([source code](https://github.com/Secretchronicles/TSC/blob/devel/tsc/src/video/video.cpp#L199)). If the game crashes with a segfault or C++ exception in debug build, the corresponding cleanup in `Exit_Game()` is not called. Thus, SFML is never told to fix the screen resolution.

This bug has mostly been worked around anyway. In release builds, TSC now has a try/catch wrapper in its `main()` function that ensures proper shutdown on a C++ exception. For segfaults, the OS just shoots down the programme. Executing further code on segfaults is something I don't want to do (at least on Linux, you can appearently register a signal handler for SIGSEV), mostly because I want an easily debuggable TSC. Anything that causes problems with the stacktraces reported by GDB is something I want to avoid. We free-time devs don't have time to deal with crashing gracefully. If TSC crashes, it should crash loudly.

> you have it backwards.

If you imply SFML should fix the screen resolution on itself magically on segfault, then I'm pretty sure it can't. `atexit()` handlers are not called on segfaults and libraries like SFML probably shouldn't install signal handlers either.

**Comment by pirate486743186** [comment] 2019-05-10 13:37
-_-..... pfffff

In general, they are two different ways for an application to go fullscreen.

One way, is by changing the resolution of the screen like here. The app says to the screen to change resolution. Then the screen changes the screen's resolution. You change the size of the box, to fit the contents. When there's a crash, you are left with the changed resolution.

Second way, you do the other possibility that is left. The application changes its own size. The resolution of the screen never changes here. The box doesn't change size, it's the content that inflates/deflates it self to fit in.... If there's a crash, the screen is already at the right resolution, no need to do anything.


Method two is preferable. I'm assuming you just used a function provided by SFML for fullscreen,  and so,it's really SFML fault here for doing fullscreen the bad way. If it's the case, you should open an issue with them, so that it gets fixed.

**Comment by Quintus** [comment] 2019-05-10 20:22
I see. Thank you for your explanations, even though I'm not convinced this is an SFML problem as SFML leaves any scaling to the application. Sure, TSC could simply not use SFML's fullscreen option with screen resolution change and instead calculate any required resizing on itself. But that's far more than a simple fix, as it probably requires lots of changes to the old and crufty video code we have in TSC. Note that TSC does not use any of SFML's video managment other than the window creation. TSC has an inherited code base (>10 years) using raw OpenGL2.

So, yes, with your approach the problem could be fixed. But it's simply not worth the effort it takes to crash gracefully. Unless you can't convince someone else from the TSC team to tackle the problem (@refi64, maybe?) I won't re-open this ticket. After all, we're still talking about a problem that only occurs if TSC crashes. Better would be if TSC didn't crash in the first place.

**Comment by refi64** [comment] 2019-05-10 22:57
Honestly if we tried to work around this it (given the current state of the codebase) it would probably take hours and end up turning all the characters purple or something.

Depending on how "hack" we want to go, a workaround (at least on POSIX systems) to the screen state being left oddly could be to have TSC actually be a wrapper program that launches (maybe a fork?) the real TSC, and the parent process will monitor it & fix the resolution. (It's slightly concerning to me that I was able to think of such a hack really quickly...)
