### ISSUE TITLE
Allow level makers to browse available music tracks...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#300] opened 2015-01-01 09:35 UTC
We should consider adding a browse option to the level settings menu that allows a level maker to either see a dropdown with available music tracks or browse the folder(s) containing the music tracks.  They really shouldn't have to type the name of the music track manually.

**Comment by Quintus** [comment] 2015-01-01 14:03
Duplicate of #14.

**Closed by Quintus** 2015-01-01 14:03 UTC
Labels: Duplicate
