### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by default0** [Secretchronicles/TSC#569] opened 2016-09-13 19:09 UTC
Tried running the game a few times just earlier.
The game kept crashing on level load.
The specific levels that crashed were lvl_8 and dj_kirby_1.
For references on what exactly I did, you can check this twitch VoD: https://www.twitch.tv/default5/v/89174685

**Comment by kirbyfan64** [comment] 2016-09-13 19:15
I'd hardly call that "sucking", considering you did 10x better than I usually do...

**Comment by default0** [comment] 2016-09-13 19:20
I still lose runs to silliness (ie Game Over-ing somewhere) and often have small messups that lose me a couple seconds, or just dumb mistakes that cause me to die close to the end of a longer level. So, yeah, I don't feel like I'm good at the game.

**Comment by datahead8888** [comment] 2016-11-04 05:46
@default0 - the video is no longer available.  Could you reupload it on a site that is not likely to take it down very quickly?  It sometimes takes a while for us to get to specific bugs, since there are a lot of open bug items at the moment.

**Comment by datahead8888** [comment] 2016-11-04 06:23
I think I have occasionally seen random crashes myself.  I should get better about recording them; they always seem to happen when I don't have time to investigate, really.  Someone probably needs to spend some time running the game and trying things out while running gdb, in order to attempt to reproduce some of these crashes.  I think we have some issues with this, still.

**Comment by default0** [comment] 2016-11-04 06:54
Don't have this video file locally, sorry
Can try running it a couple times and then uploading to youtube.

**Comment by datahead8888** [comment] 2016-11-26 23:58
@default0 - have you had a chance to try to reproduce this bug again?  We are really eager to knock out any remaining major causes of crashes.

**Comment by default0** [comment] 2016-11-28 10:14
I just did, highlighted it on twitch this time, so it should stay around: https://www.twitch.tv/default5/v/103902611

**Comment by Quintus** [comment] 2016-12-03 20:41
This video is stuttering a lot for me, is this correct? The crash is at the end of the video, right?

**Comment by default0** [comment] 2016-12-04 21:37
The crash is at the end of the video, yes.
As for further information: it pretty much exclusively happens when the game loads dj_kirby_1, I think it happened once on loading lvl_8, but dj_kirby_1 loading is what mainly causes the crashes.

**Comment by Quintus** [comment] 2019-07-05 16:00
Can this problem still be reproduced? My Internet access is too spotty
for watching videos at the moment...

-- 
Blog: https://mg.guelker.eu

**Comment by Quintus** [comment] 2019-07-15 19:14
No answer from OP, closing. Re-open if the problem still exists.

**Closed by Quintus** 2019-07-15 19:14 UTC
Labels: Bug, Invalid
