### ISSUE TITLE
Bug when loading tower_1

### ISSUE THREAD

**Issue by kirbyfan64** [Secretchronicles/TSC#413] opened 2015-04-18 18:01 UTC
If I try to go to level `tower_1`, TSC crashes and says the level filename is empty.

Also, when I finished the level before, the yellow dots showing the levels on the world map *disappeared*.

**Comment by DarkAceZ** [comment] 2015-04-18 18:03
Duplicate of #410 and has been fixed in devel.

**Closed by DarkAceZ** 2015-04-18 18:03 UTC
