### ISSUE TITLE
Where is the save file located on Windows

### ISSUE THREAD

**Issue by Raj2032** [Secretchronicles/TSC#662] opened 2019-08-14 10:18 UTC
I am curious to know where the safe file is located on Windows?

**Comment by Quintus** [comment] 2019-08-14 14:53
1. Please don't use the tracker for questions. We have [a forum](https://lists.secretchronicles.org/hyperkitty/list/tsc-devel@lists.secretchronicles.org/) and [a mailing list](https://lists.secretchronicles.org/postorius/lists/tsc-devel.lists.secretchronicles.org/) for that, as outlined in the README.

2. It's in `%APPDATA%\tsc\savegames`, as required by Windows directory guidelines. `%APPDATA%` is a hidden folder usually in `C:\Users\<username>\AppData\Roaming` if I remember correctly. You need to enable some option in Windows Explorer to show hidden folders.

Closing as this is not a bug or feature request. Follow up on the forum or mailing list if this doesn't clear things up for you.

**Closed as completed by Quintus** 2019-08-14 14:53 UTC
Labels: Invalid
