### ISSUE TITLE
TSC start error on ReactOS 32bit and WinXP 32bit, GetTickCount64 function does not exist

### ISSUE THREAD

**Issue by xet7** [Secretchronicles/TSC#661] opened 2019-08-04 21:32 UTC
Hi,
originally discussed at mailing list, I moved to here to add screenshots.

When using TSC 32bit installer from:
https://ftp.secretchronicles.org/alpha/

There is this error popup:

tsc.exe - Entry Point Not Found
The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll.

## ReactOS 32bit

![tsc-reactos-error](https://user-images.githubusercontent.com/15545/62429526-70bc5680-b718-11e9-89a5-8e6bfba2e704.png)

## WinXP 32bit

![winxp-error2](https://user-images.githubusercontent.com/15545/62429533-7f0a7280-b718-11e9-8b4d-51cb2b0d8996.png)

**Comment by xet7** [comment] 2019-08-04 21:54
BTW, 32bit TSC installer and 32bit game does work using wine at Debian testing 64bit

![tsc-win32-wine](https://user-images.githubusercontent.com/15545/62429763-7c5d4c80-b71b-11e9-8fc6-5e901e8ed446.png)

**Comment by Quintus** [comment] 2019-08-05 07:17
The problem is that WinXP is too old, see [refi's statement](https://lists.secretchronicles.org/hyperkitty/list/tsc-devel@lists.secretchronicles.org/message/FMMK4SYBUEF6ZF5EXFM7KJD27IVOMBBX/).

Closing because Windows XP is unsupported by TSC.

**Closed as completed** 2019-08-05 07:17 UTC
Labels: Bug, Wontfix

**Comment by xet7** [comment] 2019-12-04 19:21
Well, I tried, but did not get this working.

## 1) MSYS2 32bit WinXP

It seems MSYS2 does not support WinXP anymore https://github.com/msys2/MINGW-packages/issues/5139

## 2) ReactOS

I did try to modify ReactOS to get TSC running. So I copied GetTickCount64 function from kernel32_vista.dll to kernel32.dll. Those vista named dll code are from wine. This is also related to Compatibility Mode:
https://reactos.org/wiki/User:Petr-akhlamov/Compatibility_mode

In compatibility mode, it's possible to change application exe properties for compatibility to Win7 and other versions of Windows. But in compatibility mode GetTickCount64 code is not activated. That GetTickCount64 code only works when it's copied to kernel32.dll and compatibility mode is not in use. There is also more compatibility mode settings or "shims" to enable separately in compatibility mode settings.

According to ReactOS Jira tickets, ReactOS developers seem to prefer that current kernel32.dll code would be left as it is, to keep current ReactOS compatibility, and all these workarounds to be implemented in compatibility mode and shims:
https://github.com/reactos/reactos/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+shim

There are many already implemented shims, but I did not figure out yet how to add a new shim.

Another way would be to add some shims to be used at specific executeable.

As could be seen from ReactOS Jira tickets, adding GetTickCount64 does make for example Notepad++ working. But comments in ReactOS forum and Jira tickets do say that this is too big hack and can break more that it would fix.

After fixing GetTickCount64, then there did come some other error about missing function. And after that, 3rd one missing function, that I was not able to fix yet.

It seems that I have not yet figured yet what would be correct way to add compatibility to ReactOS so that it would be acceptable enough to be included into ReactOS.

I did not go deeper into this rabbit hole yet, seems too time consuming.
