### ISSUE TITLE
Map Movement Glitch...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#315] opened 2015-01-04 13:20 UTC
I found that after loading a save state file in a level, exiting, and travelling to a spot on the world map, I could not move to the left.  After repeatedly trying to move, Alex finally budged.  See the video for details.

Notice the jerking motion about 18 minutes into the video - this is me trying to move left, though the jerking motion may not be obvious through the entire video.

Video: https://www.youtube.com/watch?v=MiiM-AOT1JY&feature=youtu.be

Save State File used in the video:
https://drive.google.com/open?id=0B6YSsocq3-cWYUtaTjVqcEVFRjg&authuser=0

**Comment by sydneyjd** [comment] 2015-01-08 23:56
I think i had this once before. I dont know how to recreate it though.

**Comment by Quintus** [comment] 2018-08-04 12:01
This isn't related to saving. The bug can be reproduced without saving, and the reason behind it is the bad design of how world points are connected. They use a special line object that connects points, and sometimes the collision algorithm doesn't get the collision with the line right.

The "proper" solution, as so often, is to rewrite the concept and do not use such lines at all.

**Comment by Quintus** [comment] 2018-08-04 13:14
Well, it's easier. This specific waypoint in World 1 can simply be fixed by changing the line that leads to the previous waypoint.

**Closed** 2018-08-04 13:36 UTC
Labels: Bug
