### ISSUE TITLE
Graphics Glitch in World Map at certain way points

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#231] opened 2014-10-11 01:42 UTC
I know this bug happens if the following steps are done.  Someone will eventually want to verify under what simpler conditions it happens.  I just want to get it logged for now:
- Go to the final waypoint in the game that displays the credits if entered
- Save your game, quit, and load the save state
- Press escape to view the menu
- Press escape again to return to the world map.  Over half the map does not display correctly, showing nothing but green.

It happens if you press escape on other way points, too, but I had saved while on the credits waypoint.

This is NOT the bug we have logged about credits scrolling forever and having their text overlap each other...this is a world map bug.

**Comment by Quintus** [comment] 2018-08-03 12:29
Confirmed this still exists. It doesn't have to do something with saving, though. You can reproduce the issue by just entering world 1 and moving to the waypoint for lvl_6. Then enter and leave the ESC menu. The issue should now be seeable; several parts of the map are not drawn. Once you move in a way that moves the camera, however, things return to normal.

Looks like a full redraw of the map is missing when the menu is left.

**Comment by Quintus** [comment] 2018-08-03 12:47
Neither redrawing all sprites in the map nor updating the camera fixes this O_o

**Comment by Quintus** [comment] 2018-08-03 12:52
When leaving the Menu, `cOverworld::Enter()` is called from `Enter_Game_Mode()`. A solution that works by redrawing something should thus go into `cOverworld::Enter()` probably.

**Closed** 2018-08-03 15:05 UTC
Labels: Bug
