### ISSUE TITLE
Allow level makers to select background images...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#301] opened 2015-01-01 10:54 UTC
In the Settings menu for a level, there should be an option to browse available background images for each layer, either browsing the file system or using a dropdown.  The user really shouldn't have to type it manually unless they so choose.

**Comment by Quintus** [comment] 2015-01-01 14:04
Duplicate of #14.

**Closed by Quintus** 2015-01-01 14:04 UTC
Labels: Duplicate

**Comment by datahead8888** [comment] 2015-01-01 14:07
I had thought that planned file selector was just for something with save state files.  We probably need to list what file selections we want to replace in that ticket to be clearer.
