### ISSUE TITLE
Full Screen Mode Broken for Some Linux Distros...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/TSC#331] opened 2015-01-10 01:30 UTC
This is a problem that @xet7 discovered.  I found I have the problem, too.  @sydneyjd said he does not encounter this problem.

Start out in windowed mode.
Select Options -> Video and set full screen to on.

You will find that you enter a full screen mode in which the TSC display is a smaller "subwindow" of the full screen display.  I cannot seem to find a way to get a screen shot.  The Ubuntu screen shot system doesn't work in full screen mode, and screen shots from TSC only show the normal TSC window as if full screen mode was never used.

* I am running Ubuntu 12.04.4 LTS and have the problem.
* xet7 is running Linux Mint 17.1 64bit (it's based on Ubuntu 14.04.)  His screen resolution is 1920x1200 on external monitor, and 1366x768 on internal.
* sydney is running Debian Jessie and does not have the problem.

cc @Luiji (since you had a bit different full screen ticket you opened)

**Comment by sydneyjd** [comment] 2015-01-10 02:38
@datahead8888 to see your monitor settings in ubuntu 12.04 open the
settings panel ("settings" i think) and click on "monitors" or
"screens". That is if you are using Unity.

**Comment by Luiji** [comment] 2015-01-16 15:38
It might be worth not using true full screen mode by default (though we can keep it as an option) and instead using pseudo-fullscreen, which is when you make a borderless window cover the entire screen. In my experience this tends to cause significantly less problems, and with modern graphics cards there's no noticeable performance penalty.

At the very least, I think it's worth considering not making fullscreen the default. When switching to fullscreen mode it should show a dialog stating "Are you sure you want to continue like this?" for 5 seconds before automatically reverting. This also makes it so that if the program crashes (as in my report #242) the fullscreen mode isn't saved in the settings.

**Comment by sydneyjd** [comment] 2015-01-16 15:53
Yes, i don’t think fullscreen should be default either. I have had
issues with it reverting to my normal resolution after going full screen.

**Comment by datahead8888** [comment] 2015-01-16 20:21
I may have not set the proper resolution before going to full screen.  I will have to try playing with that when I get some more time.  I wound up a bit swamped when I finally reached some musicians for TSC and with some grad school craziness going on.  I could then check again with xet7 to see if he's still having trouble with it.

If we have a true full screen and a windowed full screen (if that's the right word), we'd want to make sure the options are clearly labeled in the menus.

**Comment by xet7** [comment] 2015-01-16 22:36
Before this bug last year TSC did start fullscreen with lower resolution, but that does not work anymore.

I just tested, when I start TSC it was still windowed mode, but when I setup TSC resolution to be the same max resolution of my external monitor 1920x1200 then I did get game playing fullscreen, because resolutions matched. So now I know this workaround, but I would prefer if TSC detected and setup screen resolution and this windowed fullscreen automatically.

**Comment by datahead8888** [comment] 2015-01-31 05:25
I tried setting the resolution and then using full screen, and I properly had a full screen that used my entire monitor's screen.

> So now I know this workaround, but I would prefer if TSC detected and setup screen resolution and this windowed fullscreen automatically.

Are you saying TSC used to detect the resolution and autoset it for the full screen mode?  I'm not sure if we should maintain this ticket as a bug or close it as not-a-bug and open a new one as a feature.
cc @Quintus / @Luiji.

**Comment by Quintus** [comment] 2015-02-06 13:32
This sounds a bit weird. Some have it, some don’t. I can’t test right now, but in the meantime, could you please post the following information:

1. Do you have an AMD, NVidia, Intel, or whatever graphics card?
2. Which driver are you using for your graphics card?
3. Output of `xrandr`

The `xrandr` commands outputs your current screen settings in case you wonder what it does.

Valete,
Quintus

**Comment by Luiji** [comment] 2015-02-07 01:11
Intel card, default drivers from the Linux kernel and X.org userlands, and here:

~~~
Screen 0: minimum 320 x 200, current 1024 x 1280, maximum 32767 x 32767
VGA1 connected 1024x1280+0+0 left (normal left inverted right x axis y axis) 376mm x 301mm
   1280x1024      60.0*+   75.0  
   1152x864       75.0  
   1024x768       75.1     60.0  
   800x600        75.0     60.3  
   640x480        75.0     60.0  
   720x400        70.1  
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
~~~

At some point I'll test full screen mode when in normal orientation.

**Comment by xet7** [comment] 2015-02-07 13:44
I have Lenovo ThinkPad Edge 0301DFG laptop with Inter graphics card:
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 12)
It's running OpenGL v2.1 Mesa 10.1.3.

```bash
xrandr
Screen 0: minimum 320 x 200, current 1920 x 1200, maximum 32767 x 32767
LVDS1 connected (normal left inverted right x axis y axis)
   1366x768       59.6 +   50.0  
   1360x768       59.8     60.0  
   1024x768       60.0  
   800x600        60.3     56.2  
   640x480        59.9  
VGA1 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200      60.0*+
   1920x1080      60.0 +
   1600x1200      60.0  
   1680x1050      60.0  
   1280x1024      60.0  
   1440x900       59.9  
   1280x960       60.0  
   1024x768       60.0  
   800x600        60.3  
   640x480        60.0  
HDMI1 disconnected (normal left inverted right x axis y axis)
DP1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)```

**Comment by Quintus** [comment] 2016-01-07 09:44
Does the problem persist with the SFML port (code in `feature-sfml-port2` branch)?

Valete,
Quintus

**Comment by xet7** [comment] 2016-01-07 10:34
Hi,
I tried to compile, what does this error mean?

[ 98%] Building CXX object CMakeFiles/tsc.dir/src/input/mouse.cpp.o
/home/lauri/TSC/tsc/src/input/mouse.cpp: In member function ‘bool
TSC::cMouseCursor::Handle_Event(const sf::Event&)’:
/home/lauri/TSC/tsc/src/input/mouse.cpp:164:10: error: ‘MouseWheelScrolled’
is not a member of ‘sf::Event’
     case sf::Event::MouseWheelScrolled: {
          ^
/home/lauri/TSC/tsc/src/input/mouse.cpp:165:16: error: ‘const class
sf::Event’ has no member named ‘mouseWheelScroll’
         if (ev.mouseWheelScroll.wheel == sf::Mouse::VerticalWheel &&
                ^
/home/lauri/TSC/tsc/src/input/mouse.cpp:165:42: error: ‘VerticalWheel’ is
not a member of ‘sf::Mouse’
         if (ev.mouseWheelScroll.wheel == sf::Mouse::VerticalWheel &&
                                          ^
/home/lauri/TSC/tsc/src/input/mouse.cpp:166:35: error: ‘const class
sf::Event’ has no member named ‘mouseWheelScroll’
             Handle_Mouse_Wheel(ev.mouseWheelScroll.delta)) {
                                   ^
make[2]: *** [CMakeFiles/tsc.dir/src/input/mouse.cpp.o] Error 1
make[1]: *** [CMakeFiles/tsc.dir/all] Error 2
make: *** [all] Error 2

BR,
xet7

**Comment by Quintus** [comment] 2016-01-07 12:58
It means that your version of SFML is too old (2.3+ required): http://www.sfml-dev.org/tutorials/2.3/window-events.php#the-mousewheelmoved-event

/cc @lambda-11235

Vale,
Quintus

**Comment by xet7** [comment] 2016-01-07 20:10
@Quintus 

Ok after installing binary x64 version of SFML, and trying to compile, then I got this error, what to do now? Should I have compiled from source?

```bash
[100%] Building CXX object CMakeFiles/tsc.dir/credits.cpp.o
Linking CXX executable tsc
/usr/local/lib/libsfml-audio.so: undefined refence to target ”std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20”
collect2: error: ld returned 1 exit status
make[2]: *** [tsc] Error 1
make[1]: *** [CMakeFiles/tsc.dir/all] Error 2
make: *** [all] Error 2
```

BR,
xet7

**Comment by Quintus** [comment] 2016-01-07 22:21
Now that looks weird. Did you wipe your TSC build directory after you
installed the other version of SFML or may it be that this is some rest
from previously compiled source files?

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by xet7** [comment] 2016-01-07 22:23
Ok I try again with empty build directory, it's now compiling.

**Comment by xet7** [comment] 2016-02-21 06:03
@Quintus
I compiled newest SFML master and TSC devel branch from from GitHub sources today. TSC starts in windowed mode. When I select fullscreen for default 1024x768 resolution and apply changes, fullscreen works, and I do not need to increase screen resolution of TSC. When I exit TSC, and start again, it then starts fullscreen. Should TSC start at fullscreen mode by default ?

**Comment by Quintus** [comment] 2016-02-21 11:39
Okay, thank you for testing. Good to know the problem is resolved with
SFML.

TSC starts in the mode that was in use the last time you run TSC. If you
start if for the first time with a clean config, it will start in
windowed mode with resolution 800x600, see
https://github.com/Secretchronicles/TSC/blob/feature-sfml-port2/tsc/src/video/video.cpp#L213. This
is intended behaviour, but if everybody wants it to start in full-screen
by default, we can change that.

Vale,
Quintus

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by xet7** [comment] 2016-02-21 11:58
@Quintus
When I installed TSC for friend family kid, first question from him was how to make it run fullscreen. I would think most game players like to play games in fullscreen mode, but I only know about my own and some friends usage. It would be nice for some others at TSC team to comment.

**Comment by Quintus** [comment] 2016-07-23 19:59
Since it appearently works in the SFML port, why wasn't this closed...? Closing.

Valete,
Quintus

**Closed by Quintus** 2016-07-23 19:59 UTC
Labels: Bug

**Comment by datahead8888** [comment] 2016-07-24 03:45
> Since it appearently works in the SFML port, why wasn't this closed.

We have a lot of tickets open, and everyone gets busy.  I think it makes sense to keep most of them open if we think they represent possible work, though it is good to review them every so often as you are doing.

I think we should attempt to test for this ticket again.  I could try to do it later when I get a chance.

**Comment by datahead8888** [comment] 2016-08-03 04:36
I didn't see that xet7 said this issue is resolved for him before.  However, I just tried it now, and it is broken for me -- I see a "subwindow" of TSC inside a larger, white full screen window.  If this is an issue, it should be under a new ticket, however.
