### ISSUE TITLE
Low fps e.g. when a fire ball bounces

### ISSUE THREAD

**Issue by HybridDog** [Secretchronicles/TSC#524] opened 2016-01-23 12:39 UTC
SMC didn't have the problem.
In some situations the screen (or even the game) freezes for a few ms.
For example when the fire ball (shot by maryo with fire berry) bounces on the ground or gets removed when it touches a wall or when the third berry is eaten and a lot balls appear at once, it freezes.
To test it you can press ctrl+p, press esc to reset max and worst fps and then
see how worst fps suddenly decreases to about 27 when the fireball bounces.
Moving the texture and the geometry quality sliders in the setting doesn't have an effect on the problem.
l didn't enable vsync in the tsc settings but my driver radeon obviously automatically enables it everywhere.

The problem is really annoying, l don't want to play tsc because of it and because loading some levels takes very long, l need to wait seeing black until l can play.

**Comment by Quintus** [comment] 2016-01-23 15:07
Duplicate of #96 and #95.

Valete,
Quintus

**Closed by Quintus** 2016-01-23 15:07 UTC
Labels: Duplicate

**Comment by HybridDog** [comment] 2016-01-24 10:13
>Duplicate […]

sorry, l searched for fps and didn't find issues
l don't only get the lags when a fireball bounces, there are other situations, e.g. sometimes when maryo hits a box containing blue crystals.

**Comment by Quintus** [comment] 2016-01-24 12:22
It is likely that this is the same issue as they’re handled similaryly internally. Thank you for your report anyway, we need to get working on this sometime :-)

Vale,
Quintus
