### ISSUE TITLE
compiler flags for c++11 support

### ISSUE THREAD

**Issue by dargor0** [Secretchronicles/TSC#548] opened 2016-07-25 02:01 UTC
Hi. I was trying to compile TSC under Debian Sid, g++ 5.4.0, from latest stable tarball (TSC-2.0.0). I got compilation errors due to missing -std=gnu++11 flag. As suggested in the cmake documentation, I added 

`set (CMAKE_CXX_STANDARD 11)`

In CMakeLists.txt file and it worked. It seems that cmake didn't included the required flag for my g++ version. 
I checked git version and it seems fixed in line 59:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wno-deprecated-declarations")`

However IMHO, I think my change is cleaner than putting the flag directly. Thanks.

**Comment by Quintus** [comment] 2016-07-25 12:59
> However IMHO, I think my change is cleaner than putting the flag directly. Thanks.

Yes, it is. We'll change that.

> rom latest stable tarball (TSC-2.0.0)

It is likely you run into a problem with TSC only showing a black screen on startup (cf. ticket #500). The problem is fixed in devel by upgrading to CEGUI 0.8.x.

Vale,
Quintus

**Comment by Quintus** [comment] 2016-07-27 11:42
I correct myself. We'll not change this. Reason: When I use `set (CMAKE_CXX_STANDARD 11)` it does **not** pass `-std=c++11` to the compiler, but `-std=gnu++11`. This is **not** C++11. This is C++11 with GNU extensions. I definitely don't want nonstandard extensions enabled by default. I enable them when I need them and want a compilation error if I used them without explicitely asking for them. This is in my opinion a highly erratic behaviour of CMake. It definitely speaks against your recommendation.

Vale,
Quintus

**Comment by Quintus** [comment] 2016-07-27 11:56
I asked in the `#cmake` channel and they convinced me it is not erratic behaviour, but intended by design. If not requested otherwise, CMake always enables the compiler-specific extensions for whatever compiler it is run on. They suggested to set `CMAKE_CXX_EXTENSIONS` instead.

**Closed** 2016-07-27 12:01 UTC
Labels: Build system, Feature
